import { ArrowRight, CheckCircle, Clock } from '@phosphor-icons/react'
import { useEffect } from 'react'
import { Link, useParams } from 'react-router-dom'
import { track } from '../analytics/events'
import { ProductCard } from '../components/ProductCard'
import { GUIDES, guideBySlug, productsForGuide } from '../content/guides'
import { useCatalog } from '../data/catalog-provider'

export function GuidePage() {
  const { slug = '' } = useParams(), guide = guideBySlug(slug), catalog = useCatalog()
  useEffect(() => { if (guide) track({ event: 'view_guide', category: guide.slug }) }, [guide])
  if (!guide) return <main className="container page not-found"><p className="eyebrow">Guia não encontrado</p><h1>Esse conteúdo ainda não está disponível.</h1><Link className="button primary" to="/guias">Ver todos os guias</Link></main>
  const products = productsForGuide(guide, catalog).slice(0, 4)
  const related = guide.relatedGuideSlugs.map(guideBySlug).filter(Boolean)
  return <main className="container editorial-page guide-page"><nav className="breadcrumbs" aria-label="Navegação estrutural"><Link to="/">Início</Link> / <Link to="/guias">Guias</Link> / {guide.title}</nav><article><header className="editorial-hero"><p className="eyebrow">Guia Distrito Geek</p><h1>{guide.title}</h1><div className="guide-meta"><span><Clock/> {guide.readingMinutes} min de leitura</span><span>Atualizado em {new Date(`${guide.updatedAt}T12:00:00`).toLocaleDateString('pt-BR')}</span></div><p>{guide.intro}</p></header><nav className="article-summary" aria-label="Neste guia"><b>Neste guia</b>{guide.sections.map((section, index) => <a key={section.heading} href={`#secao-${index + 1}`}>{section.heading}</a>)}</nav><div className="article-body">{guide.sections.map((section, index) => <section id={`secao-${index + 1}`} key={section.heading}><p className="section-number">0{index + 1}</p><h2>{section.heading}</h2><p>{section.body}</p>{section.items && <ul>{section.items.map((item) => <li key={item}><CheckCircle/>{item}</li>)}</ul>}</section>)}</div><aside className="guide-category-cta"><div><small>Explore produtos relacionados</small><b>Leve o aprendizado para a sua próxima aventura</b><p>Compare produtos sincronizados e confirme as condições no marketplace.</p></div><Link className="button primary" to={guide.categoryPath}>{guide.categoryLabel} <ArrowRight/></Link></aside>{products.length > 0 && <section className="guide-products"><header className="section-title left"><p>Seleção relacionada</p><h2>Produtos reais para continuar</h2><span>Preço, estoque e link vêm dos anúncios sincronizados.</span></header><div className="product-grid">{products.map((product, index) => <ProductCard key={product.id} product={product} listId="guia" position={index + 1}/>)}</div></section>}<section className="landing-faq guide-faq"><p className="eyebrow">Dúvidas frequentes</p><h2>Perguntas sobre este tema</h2>{guide.faq.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>{related.length > 0 && <nav className="related-guides" aria-label="Guias relacionados"><b>Continue aprendendo</b>{related.map((item) => item && <Link key={item.slug} to={`/guias/${item.slug}`}>{item.title}<ArrowRight/></Link>)}</nav>}</article><aside className="editorial-sidebar"><div><b>Todos os guias</b>{GUIDES.map((item) => <Link className={item.slug === guide.slug ? 'active' : ''} key={item.slug} to={`/guias/${item.slug}`}>{item.title}</Link>)}</div></aside></main>
}
