import { ArrowSquareOut, CheckCircle, ClockCounterClockwise } from '@phosphor-icons/react'
import { Link, useParams } from 'react-router-dom'
import { money, ProductCard } from '../components/ProductCard'
import { ProductGallery } from '../components/ProductGallery'
import { useCatalog, useCatalogStatus } from '../data/catalog-provider'

export function ProductPage() {
  const { slug } = useParams(), all = useCatalog(), { loading, error } = useCatalogStatus()
  const product = all.find((p) => p.slug === slug)
  if (loading) return <main className="container page"><div className="catalog-state" role="status">Carregando produto…</div></main>
  if (error) return <main className="container page"><div className="catalog-state error" role="alert">{error}</div></main>
  if (!product) return <main className="container not-found"><p className="eyebrow">Produto indisponível</p><h1>Este item não está no catálogo ativo.</h1><Link className="button primary" to="/categoria/todos">Voltar ao catálogo</Link></main>
  const activeListings = product.listings.filter((listing) => listing.active && product.status === 'published')
  return <main className="container product-page"><nav className="breadcrumbs" aria-label="Navegação estrutural"><Link to="/">Início</Link> / <Link to={`/categoria/${product.category}`}>{product.category.replaceAll('-', ' ')}</Link> / {product.title}</nav><div className="product-top"><ProductGallery images={product.images} title={product.title} /><section className="product-info"><p className="eyebrow">{product.category.replaceAll('-', ' ')}</p><h1>{product.title}</h1><div className="price">{money(product.price)}</div><p>Preço sincronizado com o anúncio oficial.</p><div className="chips"><span>{product.attributes.Marketplace}</span><span>{product.stock > 0 ? `${product.stock} disponível(is)` : 'Consulte disponibilidade'}</span></div><ul><li><CheckCircle /> Compra protegida pelo marketplace</li><li><CheckCircle /> Imagens e condições do anúncio oficial</li><li><ClockCounterClockwise/> Sincronizado em {new Date(product.updatedAt).toLocaleDateString('pt-BR')}</li></ul>{activeListings.map((listing) => <a key={listing.externalId} className={`button buy ${listing.marketplace}`} href={listing.url} target="_blank" rel="noopener noreferrer">Comprar no {listing.marketplace === 'mercado-livre' ? 'Mercado Livre' : listing.marketplace === 'shopee' ? 'Shopee' : 'marketplace'} <ArrowSquareOut /></a>)}{!activeListings.length && <div className="unavailable" role="status">Este anúncio está pausado ou encerrado. A compra pelo marketplace não está disponível.</div>}</section></div><section className="description"><h2>Descrição</h2><p>{product.description}</p><h3>Informações adicionais</h3><dl>{Object.entries(product.attributes).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section><section className="related"><header className="section-title left"><p>Continue explorando</p><h2>Produtos relacionados</h2></header><div className="product-grid">{all.filter((p) => p.status === 'published' && p.id !== product.id).slice(0, 4).map((p) => <ProductCard key={p.id} product={p} />)}</div></section></main>
}
