import type { Product } from '../domain/product.ts'

/**
 * Clusters temáticos do hub /guias. A ordem aqui é a ordem de exibição.
 *
 * Cada guia pertence a um cluster e tem uma intenção de busca principal. Duas páginas do
 * site nunca devem disputar a mesma consulta: as landings em `src/seo/landing-pages.ts`
 * atendem intenção comercial ("miniaturas rpg 32mm"), os guias atendem intenção
 * informacional ("como usar goblins no rpg"). Antes de criar guia novo, confira se algum
 * existente já cobre a intenção e expanda em vez de duplicar.
 */
export const GUIDE_CLUSTERS = [
  { id: 'miniaturas', label: 'Miniaturas', description: 'Escala, material, preparação, pintura e conservação das peças que vão para a mesa.' },
  { id: 'rpg-mesa', label: 'RPG de Mesa', description: 'O básico para quem está começando: como funciona uma mesa, o que é preciso e como dar o primeiro passo.' },
  { id: 'dnd', label: 'D&D', description: 'Dungeons & Dragons na prática, do primeiro encontro à escolha das miniaturas.' },
  { id: 'pathfinder', label: 'Pathfinder', description: 'Como o sistema usa o grid e o que muda na escolha das peças.' },
  { id: 'mestre', label: 'Mestre de RPG', description: 'Preparar sessões, montar encontros e escolher o que realmente vale ter na caixa.' },
  { id: 'criaturas', label: 'Criaturas', description: 'Goblins, orcs, mortos-vivos e outros inimigos recorrentes das campanhas.' },
] as const

export type GuideClusterId = (typeof GUIDE_CLUSTERS)[number]['id']

export type EditorialGuide = {
  slug: string
  /** Cluster do hub. Define onde o guia aparece em /guias. */
  cluster: GuideClusterId
  /** Guia pilar do cluster de miniaturas: aparece em destaque no topo do hub. */
  pillar?: boolean
  title: string
  seoTitle: string
  seoDescription: string
  updatedAt: string
  readingMinutes: number
  intro: string
  /**
   * `items` vira bloco de destaque (card com borda amarela). `links` vira link contextual
   * logo depois do parágrafo — é assim que a malha do cluster se forma, sem bloco artificial
   * de links no fim da página.
   */
  sections: Array<{ heading: string; body: string; items?: string[]; links?: Array<{ label: string; to: string }> }>
  faq: Array<{ question: string; answer: string }>
  relatedGuideSlugs: string[]
  categoryPath: string
  categoryLabel: string
  productKeywords: string[]
}

export const GUIDES: EditorialGuide[] = [
  {
    slug: 'miniaturas-rpg', cluster: 'miniaturas', pillar: true, title: 'Miniaturas RPG: guia completo para começar', seoTitle: 'Miniaturas RPG: Guia Completo para Começar', seoDescription: 'Entenda para que servem as miniaturas de RPG, qual escala escolher, diferenças de material e quantas peças um grupo realmente precisa.', updatedAt: '2026-08-09', readingMinutes: 10,
    intro: 'Miniatura de RPG é a peça que representa um personagem, um NPC ou um inimigo em cima da mesa. Ela não é obrigatória para jogar, mas resolve um problema concreto: quando quatro pessoas discutem quem está flanqueando quem, apontar para o tabuleiro encerra a dúvida em dois segundos. Este guia reúne o essencial para quem está montando a primeira coleção e aponta, em cada tema, o material mais detalhado que já publicamos.',
    sections: [
      { heading: 'Para que a miniatura serve na prática', body: 'O ganho principal é espacial. Sistemas com grid usam distância para alcance de magia, deslocamento e linha de visão, e a miniatura transforma essas regras em algo visível. Fora do combate, ela também ajuda a fixar quem é quem numa mesa com muitos NPCs. Vale separar duas funções que costumam se misturar: a peça de personagem, que acompanha o jogador por toda a campanha, e a peça de inimigo, que aparece num encontro e volta para a caixa.', items: ['Peça de personagem: uma por jogador, escolhida com calma.', 'Peça de inimigo: em quantidade, para representar grupos.', 'Peça de destaque: chefes e criaturas grandes, usadas com menos frequência.'] },
      { heading: 'É obrigatório jogar com miniaturas?', body: 'Não. Muitas mesas jogam bem com descrição verbal, e alguns sistemas foram desenhados para funcionar sem grid. Rascunhos em papel, fichas, dados ou moedas cumprem a função de marcar posição. A miniatura entra quando a mesa quer mais clareza tática ou quando o grupo tem prazer no objeto em si — pintar, colecionar, montar cenário. Começar pequeno e crescer conforme a necessidade evita gastar com peças que ficam na gaveta.' },
      { heading: 'Qual escala escolher', body: 'As escalas mais comuns em RPG de mesa são 28 mm e 32 mm, que equilibram presença visual e espaço no tabuleiro. Peças maiores, na faixa de 75 mm, existem para pintura e exposição, não para o grid. O número não corresponde à altura total da peça, e é aí que a maioria das compras dá errado: uma pose curvada ou uma arma levantada muda a altura sem mudar a escala do personagem.', links: [{ label: 'Guia completo de escala: 28 mm, 32 mm e 75 mm', to: '/guias/escala-miniaturas-rpg-28mm-32mm-75mm' }] },
      { heading: 'Resina ou outros materiais', body: 'Resina registra detalhes muito pequenos com nitidez, o que aparece em armaduras, escamas, tecidos e rostos. Em troca, é mais rígida que plásticos flexíveis e exige mais cuidado com quedas e com partes finas como espadas e asas. Peças impressas em resina normalmente chegam sem pintura, o que é uma vantagem para quem quer personalizar e uma etapa extra para quem quer usar na mesa no mesmo dia.', links: [{ label: 'Como cuidar e conservar peças de resina', to: '/guias/cuidados-miniaturas-resina' }] },
      { heading: 'Preparar e pintar', body: 'Miniatura sem pintura permite escolher as cores do seu personagem em vez de aceitar as de fábrica. O processo tem uma ordem que compensa respeitar: inspeção, limpeza, primer, camadas finas de cor, sombras e acabamento. O erro mais comum de iniciante é tinta grossa, que preenche justamente as texturas que tornam a escultura interessante.', links: [{ label: 'Como preparar e pintar miniaturas de resina', to: '/guias/como-pintar-miniaturas-resina' }] },
      { heading: 'Miniaturas em D&D e em Pathfinder', body: 'Os dois sistemas usam grid e ambos funcionam com as mesmas peças de fantasia — não existe miniatura exclusiva de um ou de outro. A diferença prática está no volume de inimigos que cada mesa costuma colocar em campo e na frequência de criaturas de tamanho grande. Peças compradas para uma campanha se reaproveitam na outra sem problema.', links: [{ label: 'Quais miniaturas comprar para começar em D&D', to: '/guias/miniaturas-para-comecar-campanha-dnd' }, { label: 'Como escolher miniaturas para Pathfinder', to: '/guias/como-escolher-miniaturas-pathfinder' }] },
      { heading: 'Como montar a primeira coleção', body: 'Comece pelo que entra em cena toda semana, não pelo que é mais bonito na foto. Na prática isso significa uma peça por personagem do grupo e um conjunto de inimigos comuns que sirva para vários encontros — goblins, bandidos, esqueletos. Chefes e criaturas grandes podem esperar, porque aparecem poucas vezes por campanha. Um kit com várias peças costuma custar menos por miniatura do que comprar uma a uma.', items: ['Primeiro: uma peça para cada jogador da mesa.', 'Depois: um grupo de inimigos repetíveis.', 'Por último: chefes, criaturas grandes e peças de exposição.', 'Compare medidas com o que você já tem antes de comprar.'] },
    ],
    faq: [
      { question: 'Precisa usar miniaturas para jogar RPG?', answer: 'Não. A miniatura ajuda quando a mesa quer clareza tática ou gosta do objeto, mas descrição verbal, fichas e rascunhos cumprem a função de marcar posição.' },
      { question: 'Qual o tamanho mais comum de miniatura de RPG?', answer: 'As faixas de 28 mm e 32 mm são as mais usadas em mesa, porque equilibram visibilidade e espaço no tabuleiro.' },
      { question: 'Miniaturas de 28 mm e 32 mm podem ser usadas juntas?', answer: 'Podem, sobretudo quando representam criaturas de alturas diferentes. Para um grupo visualmente uniforme, compare altura e diâmetro da base antes.' },
      { question: 'Quantas miniaturas um mestre precisa?', answer: 'Depende do estilo da campanha. Um ponto de partida razoável é uma peça por personagem do grupo e um conjunto de inimigos comuns que sirva para vários encontros.' },
      { question: 'Miniatura de resina pode ser pintada?', answer: 'Sim, e é o uso mais comum, já que as peças costumam ser vendidas sem pintura. Vale aplicar primer antes e trabalhar em camadas finas.' },
    ],
    relatedGuideSlugs: ['escala-miniaturas-rpg-28mm-32mm-75mm', 'miniaturas-para-comecar-campanha-dnd', 'como-jogar-dnd', 'como-pintar-miniaturas-resina', 'cuidados-miniaturas-resina', 'como-escolher-miniaturas-pathfinder'], categoryPath: '/miniaturas-rpg', categoryLabel: 'Ver miniaturas RPG', productKeywords: ['miniatura', 'rpg', 'resina'],
  },
  {
    slug: 'o-que-e-rpg-de-mesa', cluster: 'rpg-mesa', title: 'O que é RPG de mesa e como funciona?', seoTitle: 'O que é RPG de Mesa e Como Funciona?', seoDescription: 'RPG de mesa é uma história construída em grupo, com regras e dados para resolver o que é incerto. Entenda os papéis, a estrutura e o que é preciso.', updatedAt: '2026-08-09', readingMinutes: 8,
    intro: 'RPG de mesa é um jogo de história contada em grupo. Uma pessoa descreve o mundo e as situações; as outras dizem o que seus personagens fazem. Quando o resultado de uma ação é incerto, os dados decidem. Não há tabuleiro obrigatório, nem placar, nem vencedor no fim — o que existe é uma narrativa que muda conforme as escolhas da mesa. Uma partida acontece em volta de uma mesa real ou por chamada de vídeo, e dura em média de duas a quatro horas.',
    sections: [
      { heading: 'Como funciona uma partida', body: 'A estrutura é uma conversa organizada por regras. O mestre apresenta uma cena: uma estrada à noite, uma porta trancada, um comerciante nervoso. Os jogadores respondem descrevendo o que seus personagens fazem. Quando a ação é trivial, ela simplesmente acontece. Quando o resultado é duvidoso, entra o dado. O mestre então descreve a consequência e a cena avança. Esse ciclo se repete por horas, e é dele que sai a sensação de história viva.', items: ['O mestre descreve a situação e interpreta o mundo.', 'Os jogadores decidem as ações dos personagens.', 'Os dados resolvem o que é incerto.', 'A consequência muda a cena seguinte.'] },
      { heading: 'Qual é o papel do mestre', body: 'O mestre não joga contra o grupo. A função dele é apresentar o mundo, interpretar todos os personagens que não pertencem aos jogadores e aplicar as regras de forma consistente. Ele não decide se o grupo vence, decide como o mundo reage. Isso inclui deixar os jogadores terem boas ideias que ele não previu — muitas das melhores cenas de RPG surgem de uma solução que o mestre não tinha imaginado. A postura útil é a de um narrador curioso, não de um adversário.' },
      { heading: 'O que os jogadores fazem', body: 'Cada jogador controla um personagem: alguém com nome, história, habilidades e limitações. A maior parte do tempo de mesa não é combate, é decisão. Investigar um sumiço, negociar com um contrabandista, escolher entre dois caminhos ruins. Interpretar não exige atuação teatral; dizer "meu personagem pergunta sobre o prefeito, desconfiado" funciona tão bem quanto fazer a voz. O que sustenta a mesa é participação, não performance.' },
      { heading: 'Para que servem os dados', body: 'O dado existe para tirar da mesa a discussão sobre o que deveria acontecer. Quando um personagem tenta escalar um muro molhado, ninguém precisa argumentar se é possível: rola-se, compara-se com uma dificuldade e o resultado vale. Isso protege a história de dois problemas opostos, o jogador que sempre acerta tudo e o mestre que sempre nega. Diferentes sistemas usam dados diferentes, e vale aprender o do sistema escolhido em vez de decorar todos.' },
      { heading: 'Precisa de mapa e miniaturas?', body: 'Não. Muitas mesas jogam apenas com descrição, o que costuma ser chamado de teatro da mente. Mapa e miniaturas ajudam quando a posição importa: alcance de um feitiço, quem está cercado, quantos passos até a porta. Em combates com muitos inimigos, apontar para o tabuleiro resolve em segundos uma dúvida que a descrição verbal levaria minutos para esclarecer. É um recurso de clareza, não um requisito.', links: [{ label: 'Guia completo de miniaturas RPG', to: '/guias/miniaturas-rpg' }, { label: 'Entenda a escala das peças', to: '/guias/escala-miniaturas-rpg-28mm-32mm-75mm' }] },
      { heading: 'Sessão, aventura e campanha', body: 'Os três termos aparecem muito e descrevem escalas diferentes. Sessão é um encontro, aquele sábado à tarde em que a mesa se reuniu. Aventura é um arco com começo e fim, como resolver o que assombra um vilarejo, e pode ocupar uma ou várias sessões. Campanha é a história longa formada por várias aventuras com os mesmos personagens, às vezes durando anos. Dá para experimentar RPG com uma sessão única, sem compromisso de campanha.' },
      { heading: 'Como começar', body: 'O caminho mais curto é escolher um sistema, reunir de três a cinco pessoas, definir quem vai mestrar e marcar uma sessão curta de teste. Não é necessário ler um livro inteiro antes, nem comprar material. A primeira sessão serve justamente para descobrir o que o grupo gosta.', links: [{ label: 'Como começar a jogar RPG de mesa, passo a passo', to: '/guias/como-comecar-rpg-de-mesa' }] },
    ],
    faq: [
      { question: 'RPG de mesa é difícil de aprender?', answer: 'O básico se aprende jogando, em uma sessão. As regras completas de um sistema são extensas, mas ninguém precisa dominá-las para participar: normalmente só o mestre precisa conhecer mais a fundo.' },
      { question: 'Quantas pessoas precisam para jogar?', answer: 'O formato mais comum é um mestre e três a cinco jogadores, mas existem mesas de duas pessoas e sistemas feitos para grupos maiores.' },
      { question: 'Precisa comprar miniaturas?', answer: 'Não. Miniaturas ajudam a visualizar posição e combate, mas mesas inteiras funcionam apenas com descrição verbal ou rascunhos em papel.' },
      { question: 'Precisa ter um mestre?', answer: 'Na maioria dos sistemas, sim, porque alguém precisa apresentar o mundo e aplicar as regras. Existem jogos narrativos sem mestre, mas são a exceção.' },
      { question: 'Quanto tempo dura uma sessão?', answer: 'Entre duas e quatro horas é o mais comum. Sessões de teste podem ser mais curtas, com uma hora e meia já rendendo uma cena completa.' },
    ],
    relatedGuideSlugs: ['como-comecar-rpg-de-mesa', 'como-jogar-dnd', 'miniaturas-rpg'], categoryPath: '/miniaturas-rpg', categoryLabel: 'Ver miniaturas RPG', productKeywords: [],
  },
  {
    slug: 'como-comecar-rpg-de-mesa', cluster: 'rpg-mesa', title: 'Como começar a jogar RPG de mesa', seoTitle: 'Como Começar a Jogar RPG de Mesa: Guia para Iniciantes', seoDescription: 'Do sistema à primeira sessão: como escolher o jogo, reunir o grupo, definir o mestre e separar o material necessário para começar a jogar RPG.', updatedAt: '2026-08-09', readingMinutes: 9,
    intro: 'Para jogar RPG de mesa pela primeira vez você precisa de quatro coisas: um sistema, um grupo, alguém disposto a mestrar e uma data marcada. Material vem depois, e menos do que a maioria imagina. Este guia percorre essa sequência na ordem em que ela realmente acontece, e separa com clareza o que é essencial do que é opcional.',
    sections: [
      { heading: 'Escolha um sistema', body: 'Sistema é o conjunto de regras que define como criar personagens, resolver ações e conduzir combate. Existem dezenas, com propostas muito diferentes: alguns detalham cada manobra de luta, outros priorizam narrativa e cabem em poucas páginas. Dungeons & Dragons e Pathfinder são os nomes mais conhecidos de fantasia, com muito material em português e comunidade grande, o que facilita achar respostas. Escolha um e ignore os outros no começo.', items: ['Sistemas com comunidade grande são mais fáceis de aprender.', 'Regras curtas facilitam a primeira sessão.', 'Não tente comparar cinco sistemas antes de jogar nenhum.'] },
      { heading: 'Encontre um grupo', body: 'O tamanho mais comum é um mestre e três a cinco jogadores, mas isso não é regra. Mesas de duas pessoas funcionam, e grupos de seis também, com o custo de cada jogador ter menos tempo em cena. Comece com quem você já conhece: amigos, colegas, família. Grupos formados por afinidade toleram melhor os erros de uma primeira sessão do que grupos de estranhos. Combine desde o início a frequência realista, porque agenda é o que mais mata campanha.' },
      { heading: 'Decidam quem será o mestre', body: 'Alguém precisa apresentar o mundo, interpretar os personagens que não são dos jogadores e aplicar as regras. Não precisa ser a pessoa mais experiente, e não precisa ser sempre a mesma. O que ajuda é ter lido o básico do sistema e ter alguma disposição para improvisar quando o grupo fizer algo inesperado — o que vai acontecer na primeira meia hora.' },
      { heading: 'Criem os personagens', body: 'O personagem é definido em uma ficha: quem ele é, no que é bom, no que é ruim, o que sabe fazer. A maioria dos sistemas oferece caminhos prontos para iniciantes, com escolhas pré-montadas que evitam decidir vinte coisas de uma vez. Vale fazer essa etapa junto, na mesma sessão, porque personagens criados em conjunto tendem a ter motivo para andar juntos. Um conceito em uma frase já basta para começar.' },
      { heading: 'Separem o material', body: 'A lista essencial é curta. O opcional é longo, e é aí que gasta-se dinheiro sem necessidade no início. Uma mesa completamente funcional pode acontecer com folha, lápis e um conjunto de dados compartilhado.', items: ['Essencial: fichas, algo para escrever, dados do sistema.', 'Essencial: acesso às regras, mesmo que só o mestre tenha.', 'Opcional: mapa, grid, marcadores.', 'Opcional: miniaturas, biombo, trilha sonora, cenário.'] },
      { heading: 'Miniaturas são obrigatórias?', body: 'Não são. Elas entram quando a mesa quer clareza de posição — quem alcança quem, quantos inimigos estão cercando o grupo, onde está a saída. Em combates com poucos participantes, a descrição verbal resolve. Conforme a campanha avança e os encontros ficam mais concorridos, muitos grupos passam a querer o tabuleiro. Comece sem, e compre depois de sentir falta.', links: [{ label: 'Guia completo de miniaturas RPG', to: '/guias/miniaturas-rpg' }] },
      { heading: 'Como funciona a primeira sessão', body: 'Uma primeira sessão bem calibrada é curta e tem um objetivo claro. Um formato que funciona: uma hora para criar personagens juntos, uma cena de abertura que apresenta o problema, uma investigação simples, um confronto e um gancho para a próxima vez. Evite começar com a política de três reinos. Um sumiço numa vila pequena dá menos trabalho de preparar e ensina o grupo a jogar.' },
      { heading: 'O que comprar primeiro', body: 'A ordem que economiza dinheiro é: nada, depois dados, depois regras, depois o resto. Muitos sistemas têm versões básicas gratuitas, suficientes para várias sessões. Dados custam pouco e podem ser compartilhados no começo. Miniaturas fazem sentido quando o grupo já sabe que vai continuar jogando e que gosta de combate tático — e aí um kit com várias peças costuma render mais que peças avulsas.', links: [{ label: 'Como jogar D&D, do zero', to: '/guias/como-jogar-dnd' }] },
    ],
    faq: [
      { question: 'Qual RPG é melhor para começar?', answer: 'O que tiver material em português e alguém no grupo disposto a ler as regras. Sistemas com comunidade grande facilitam tirar dúvidas durante a campanha.' },
      { question: 'Precisa comprar livros?', answer: 'Não necessariamente. Vários sistemas oferecem regras básicas gratuitas, que bastam para as primeiras sessões e às vezes para campanhas inteiras.' },
      { question: 'Precisa usar miniaturas?', answer: 'Não. São um recurso de clareza para combate e posição. Comece sem e avalie depois se o seu grupo sente falta.' },
      { question: 'Quantos dados preciso?', answer: 'Depende do sistema. Um conjunto pode ser compartilhado pela mesa no início; conforme o grupo se firma, cada jogador costuma querer o seu.' },
      { question: 'Posso jogar RPG online?', answer: 'Sim, e é bem comum. Chamada de vídeo com fichas compartilhadas funciona bem, e existem mesas virtuais com mapa e grid para quem quer o combate tático.' },
    ],
    relatedGuideSlugs: ['o-que-e-rpg-de-mesa', 'como-jogar-dnd', 'miniaturas-rpg'], categoryPath: '/kits-rpg', categoryLabel: 'Ver kits para começar', productKeywords: ['kit'],
  },
  {
    slug: 'como-jogar-dnd', cluster: 'dnd', title: 'Como jogar D&D: guia para quem nunca jogou', seoTitle: 'Como Jogar D&D: Guia para Quem Nunca Jogou', seoDescription: 'Entenda como uma mesa de D&D funciona: papéis, criação de personagem, o teste de d20, combate por turnos e o que é essencial para a primeira aventura.', updatedAt: '2026-08-09', readingMinutes: 10,
    intro: 'Dungeons & Dragons é um RPG de fantasia em que um mestre conduz a história e os outros participantes interpretam aventureiros. A mecânica central é simples de descrever: quando o resultado de uma ação é incerto, rola-se um dado de vinte faces, soma-se um valor do personagem e compara-se com uma dificuldade. Praticamente tudo o mais no sistema é variação em cima disso. Este guia cobre o suficiente para você entrar numa mesa sem ter lido nada antes.',
    sections: [
      { heading: 'O que é D&D', body: 'É o RPG de mesa mais conhecido do mundo, ambientado em cenários de fantasia com magia, criaturas e masmorras. Existe em várias edições, e as regras mudam entre elas — por isso vale confirmar qual edição a sua mesa usa antes de estudar qualquer detalhe. O que se mantém em todas é a estrutura: um mestre, um grupo de aventureiros, dados para resolver incertezas e uma progressão em que os personagens ficam mais capazes ao longo da campanha.' },
      { heading: 'O que você precisa para jogar', body: 'Menos do que parece. Um jogador pode participar da primeira sessão sem ter comprado nada, usando uma ficha impressa e emprestando dados. O mestre é quem precisa de acesso às regras.', items: ['Essencial: uma ficha de personagem e algo para escrever.', 'Essencial: dados, principalmente um d20.', 'Essencial: alguém com acesso às regras da edição em uso.', 'Opcional: mapa com grid, miniaturas, marcadores.'] },
      { heading: 'Mestre e jogadores', body: 'O mestre descreve o mundo, interpreta todos os personagens que não pertencem aos jogadores e decide como as regras se aplicam nas situações que o livro não previu. Os jogadores controlam um aventureiro cada e decidem o que ele faz. É útil desfazer um mal-entendido comum: o mestre não está tentando derrotar o grupo. Ele apresenta obstáculos e depois narra honestamente o que acontece quando o grupo os enfrenta.' },
      { heading: 'Crie seu personagem', body: 'A ficha reúne quem o personagem é e no que ele é bom. Os elementos que aparecem em qualquer edição são atributos, que medem capacidades como força e inteligência; classe, que define o que o personagem sabe fazer em cena; e uma origem que explica de onde ele veio. Para a primeira mesa, escolha um conceito em uma frase e siga as opções recomendadas para iniciantes do material que você está usando. Otimizar pode esperar.' },
      { heading: 'Como os dados funcionam', body: 'O dado de vinte faces é o centro do sistema. Quando você tenta algo com resultado incerto, rola o d20, soma o modificador relevante do personagem e compara com um número de dificuldade definido pelo mestre. Resultado igual ou maior, a ação funciona. Os outros dados do conjunto aparecem principalmente para medir dano e efeitos. Não é preciso decorar tabela nenhuma para jogar a primeira sessão.' },
      { heading: 'Testes, ataques e resultados', body: 'A mesma lógica serve para três coisas que parecem diferentes. Um teste mede se você consegue realizar algo, como convencer um guarda ou escalar um muro. Um ataque mede se você acerta um alvo. Uma resistência mede se você evita um efeito ruim que já está em curso. Em todos os casos há uma rolagem, um modificador e uma dificuldade. Perceber que é sempre a mesma estrutura reduz muito a sensação de complexidade.' },
      { heading: 'Como funciona o combate', body: 'O combate acontece em turnos. Define-se a ordem de quem age, e no seu turno o personagem normalmente pode se mover e realizar uma ação — atacar, lançar magia, usar um item, tentar algo criativo. É aqui que a posição no espaço passa a importar de verdade: distância até o inimigo, quem está no alcance de uma área, se há cobertura. Muitas mesas usam mapa com grid nessa hora justamente para não discutir geometria por escrito.', links: [{ label: 'Entenda a escala das miniaturas e o grid', to: '/guias/escala-miniaturas-rpg-28mm-32mm-75mm' }] },
      { heading: 'Precisa usar miniaturas?', body: 'Não. Existem duas formas comuns de conduzir combate. No teatro da mente, o mestre descreve as posições e o grupo confia na descrição, o que é rápido e flexível. Com representação no mapa, cada participante tem um marcador e as distâncias ficam explícitas, o que ajuda quando há muitos inimigos ou magias de área. Grupos que jogam do segundo jeito com frequência acabam querendo peças próprias.', links: [{ label: 'Quais miniaturas comprar para começar em D&D', to: '/guias/miniaturas-para-comecar-campanha-dnd' }] },
      { heading: 'Como começar sua primeira aventura', body: 'Escolha uma aventura curta pronta em vez de escrever a sua. Elas existem para isso: apresentam o cenário, os personagens e os encontros já calibrados para grupos iniciantes, e liberam o mestre para aprender a conduzir em vez de inventar. Marque uma sessão de três horas, crie os personagens juntos e aceite que vocês vão errar regras. Errar regra não estraga sessão; interromper a cena por vinte minutos para procurar a regra, sim.' },
    ],
    faq: [
      { question: 'D&D é difícil para iniciantes?', answer: 'A mecânica central é uma só: rolar um d20, somar um modificador e comparar com uma dificuldade. O volume de regras é grande, mas o jogador comum usa uma fração pequena delas.' },
      { question: 'Quantas pessoas precisam para jogar?', answer: 'O formato usual é um mestre e três a cinco jogadores. Funciona com menos, e com mais o tempo de cena de cada um diminui.' },
      { question: 'Precisa ter miniaturas para jogar D&D?', answer: 'Não. Dá para conduzir todo o combate por descrição. Miniaturas ajudam quando a posição precisa ficar explícita, sobretudo com muitos inimigos em campo.' },
      { question: 'Precisa comprar todos os livros?', answer: 'Não. Há regras básicas gratuitas suficientes para começar, e normalmente só o mestre precisa do material mais completo.' },
      { question: 'Qual dado é mais usado no D&D?', answer: 'O d20, de vinte faces. Ele resolve testes, ataques e resistências. Os outros dados aparecem principalmente para medir dano.' },
    ],
    relatedGuideSlugs: ['como-comecar-rpg-de-mesa', 'miniaturas-para-comecar-campanha-dnd', 'miniaturas-rpg', 'escala-miniaturas-rpg-28mm-32mm-75mm'], categoryPath: '/miniaturas-dnd', categoryLabel: 'Ver miniaturas para D&D', productKeywords: ['d&d'],
  },
  {
    slug: 'escala-miniaturas-rpg-28mm-32mm-75mm', cluster: 'miniaturas', title: 'Escala de miniaturas RPG: diferenças entre 28 mm, 32 mm e 75 mm', seoTitle: 'Escala de Miniaturas RPG: 28mm, 32mm e 75mm', seoDescription: 'Entenda as diferenças entre miniaturas RPG de 28 mm, 32 mm e 75 mm e escolha a escala certa para mapas, pintura e coleção.', updatedAt: '2026-08-09', readingMinutes: 8,
    intro: 'A escala influencia como a miniatura ocupa o mapa, combina com outras peças e mostra detalhes depois da pintura. Embora os anúncios usem medidas como 28 mm, 32 mm e 75 mm, esses números nem sempre representam a altura total até a ponta de uma espada ou de um chifre. Eles funcionam como referência para comparar personagens humanos, bases e proporções. Antes de escolher, observe o uso principal: campanha, wargame, pintura ou exposição.',
    sections: [
      { heading: 'O que a medida realmente significa', body: 'Em miniaturas de personagens, a medida costuma partir dos pés até a linha dos olhos ou até o topo da cabeça. Fabricantes e escultores podem adotar referências diferentes. Uma pose curvada, um elmo alto ou uma arma levantada altera a altura final sem mudar a escala do personagem. Por isso, a ficha técnica, a fotografia ao lado de uma base e as dimensões informadas no anúncio são mais seguras do que interpretar apenas o número do título.', items: ['Compare a altura do personagem, não somente o cenário ou a arma.', 'Confira o diâmetro da base quando usar mapas quadriculados.', 'Para formar um grupo, prefira peças da mesma referência visual.'] },
      { heading: 'Quando escolher 28 mm ou 32 mm', body: 'As escalas de 28 mm e 32 mm são comuns em RPG de mesa e wargames porque equilibram leitura visual e espaço no tabuleiro. A miniatura de 32 mm normalmente apresenta presença um pouco maior e facilita a visualização de rosto, armadura e acessórios. Em muitas mesas as duas medidas convivem, mas a diferença pode aparecer quando personagens semelhantes ficam lado a lado. Monstros e criaturas naturalmente podem ser maiores sem quebrar a coerência da cena.' },
      { heading: 'Para que serve uma miniatura de 75 mm', body: 'Peças de 75 mm oferecem superfície maior para técnicas de pintura, luz, sombra e acabamento. Elas funcionam bem como projetos de exposição, chefes marcantes, criaturas grandes ou presentes para colecionadores. Em um mapa tradicional, porém, podem ocupar várias casas e exigir uma base maior. Antes de comprar, confira se a intenção é usar a peça durante encontros táticos ou mantê-la como destaque na estante e em sessões especiais.' },
      { heading: 'Checklist antes da compra', body: 'Uma escolha segura considera escala, dimensões finais, base, material e quantidade. Consulte todas as imagens do produto e leia o conteúdo da embalagem. Se o anúncio mostrar várias figuras, confirme se a venda inclui o conjunto completo. Na Distrito Geek, o preço e a disponibilidade vêm do anúncio sincronizado, mas medidas e condições finais devem ser conferidas no marketplace antes de concluir a compra.', items: ['Defina se a peça será usada no mapa, pintada ou exposta.', 'Compare com miniaturas que você já possui.', 'Verifique base, pose, altura total e quantidade.', 'Abra o anúncio oficial para confirmar a condição atual.'] },
    ],
    faq: [{ question: 'Miniaturas de 28 mm e 32 mm podem ser usadas juntas?', answer: 'Podem, principalmente quando representam criaturas e personagens de alturas diferentes. Para grupos visualmente uniformes, compare as dimensões e as bases.' }, { question: 'Uma miniatura 75 mm cabe em mapa de RPG?', answer: 'Depende da base e da função da peça. Ela pode representar uma criatura grande, mas geralmente ocupa mais espaço que um personagem comum.' }],
    relatedGuideSlugs: ['miniaturas-rpg', 'como-pintar-miniaturas-resina', 'miniaturas-para-comecar-campanha-dnd'], categoryPath: '/miniaturas-rpg-32mm', categoryLabel: 'Ver miniaturas por escala', productKeywords: ['32mm', '75mm', 'miniatura'],
  },
  {
    slug: 'como-pintar-miniaturas-resina', cluster: 'miniaturas', title: 'Como preparar e pintar miniaturas de resina', seoTitle: 'Como Pintar Miniaturas de Resina: Guia Prático', seoDescription: 'Aprenda a preparar, aplicar primer e pintar miniaturas de resina com segurança, preservando detalhes e melhorando o acabamento.', updatedAt: '2026-08-09', readingMinutes: 9,
    intro: 'Pintar uma miniatura de resina transforma uma peça sem pintura em personagem, criatura ou item de coleção. O resultado depende menos de equipamentos caros e mais de uma preparação cuidadosa, camadas finas e tempo de secagem. A resina costuma registrar detalhes muito pequenos, então excesso de tinta ou manuseio inadequado pode esconder justamente o que torna a escultura interessante. Este roteiro ajuda iniciantes a organizar o processo sem prometer um acabamento instantâneo.',
    sections: [
      { heading: 'Inspecione e prepare a peça', body: 'Comece observando a miniatura sob boa iluminação. Procure suportes remanescentes, pequenas rebarbas e pontos que precisem de limpeza. Use ferramentas adequadas, movimentos leves e proteção para evitar danificar partes finas. Não lixe resina sem os cuidados apropriados para partículas. Se o fabricante recomendar lavagem, siga a orientação do anúncio e deixe a peça secar completamente antes de aplicar qualquer produto.', items: ['Leia as orientações específicas do vendedor.', 'Trabalhe em local ventilado e bem iluminado.', 'Proteja mãos, olhos e vias respiratórias conforme a atividade.', 'Teste qualquer produto em uma área discreta.'] },
      { heading: 'Primer e aderência da tinta', body: 'O primer cria uma superfície mais uniforme para a tinta. Aplique camadas leves, mantendo distância e movimentação constantes quando usar spray. Uma camada espessa pode preencher texturas de tecido, escamas e armaduras. Escolha uma cor de primer coerente com o resultado: tons escuros ajudam sombras profundas, enquanto tons claros favorecem cores luminosas. Aguarde a cura recomendada pelo fabricante antes de começar a pintura.' },
      { heading: 'Construa a cor em camadas finas', body: 'Tintas acrílicas próprias para miniaturas oferecem controle, mas normalmente precisam de diluição compatível com a técnica. Em vez de tentar cobrir tudo em uma passada, aplique duas ou três camadas finas. Comece pelas áreas maiores, avance para detalhes e corrija bordas no final. Lavagens ajudam a marcar recessos; pincel seco pode destacar texturas, desde que usado com moderação. Fotografe etapas para perceber contrastes que passam despercebidos de perto.' },
      { heading: 'Finalização e conservação', body: 'Depois de concluir a pintura, deixe todas as camadas secarem. Um verniz compatível pode proteger a peça de manuseio, mas altera o brilho e deve ser aplicado conforme a recomendação do produto. Segure miniaturas pela base sempre que possível. Evite sol intenso, calor e quedas. Para peças usadas em campanha, uma caixa com divisórias reduz atrito entre espadas, cajados e outras partes delicadas durante o transporte.', items: ['Finalize olhos e pequenos detalhes somente com a base de cores pronta.', 'Use verniz fosco, acetinado ou brilhante conforme o efeito desejado.', 'Guarde a miniatura limpa, seca e sem pressão sobre partes finas.'] },
    ],
    faq: [{ question: 'É obrigatório usar primer em miniaturas de resina?', answer: 'É altamente recomendável porque melhora a aderência e ajuda a criar uma base uniforme, mas siga sempre as orientações do material e do fabricante.' }, { question: 'Qual tinta usar em miniaturas de resina?', answer: 'Tintas acrílicas formuladas para modelismo e miniaturas são uma escolha comum. Teste compatibilidade e trabalhe em camadas finas.' }],
    relatedGuideSlugs: ['miniaturas-rpg', 'escala-miniaturas-rpg-28mm-32mm-75mm', 'cuidados-miniaturas-resina'], categoryPath: '/miniaturas-resina', categoryLabel: 'Explorar miniaturas em resina', productKeywords: ['resina', 'sem pintura', 'miniatura'],
  },
  {
    slug: 'miniaturas-para-comecar-campanha-dnd', cluster: 'dnd', title: 'Quais miniaturas comprar para começar uma campanha de D&D', seoTitle: 'Miniaturas para Começar uma Campanha de D&D', seoDescription: 'Veja quais heróis, criaturas e kits priorizar ao montar a primeira seleção de miniaturas para uma campanha de D&D.', updatedAt: '2026-08-09', readingMinutes: 8,
    intro: 'Uma primeira coleção de miniaturas para D&D não precisa representar todos os monstros do livro. O conjunto mais útil é aquele que aparece repetidamente: personagens dos jogadores, inimigos versáteis e algumas criaturas que marcam encontros importantes. Planejar por função evita comprar peças bonitas que raramente chegam à mesa. Comece pelo próximo arco da campanha e amplie a coleção conforme os desafios realmente aparecem.',
    sections: [
      { heading: 'Priorize o grupo de aventureiros', body: 'Os personagens dos jogadores são as peças mais utilizadas. Procure representar classe, equipamento e personalidade sem exigir uma correspondência perfeita. Guerreiro, ladino, clérigo, patrulheiro, bárbaro e mago formam uma base versátil para diferentes grupos. Se os personagens mudarem de equipamento durante a campanha, a miniatura ainda pode funcionar como referência visual. O objetivo é facilitar posições, alcance e identificação durante o encontro.', items: ['Escolha silhuetas diferentes para reconhecer cada personagem.', 'Considere a escala e o tamanho das bases.', 'Converse com os jogadores antes de definir a aparência.'] },
      { heading: 'Escolha inimigos que possam ser reutilizados', body: 'Goblins, esqueletos, mortos-vivos e guerreiros genéricos aparecem em muitos cenários e podem representar criaturas semelhantes quando necessário. Kits com poses variadas dão movimento ao encontro e costumam ser mais úteis do que várias cópias idênticas. Antes de comprar um conjunto, confira a quantidade exata, as peças incluídas e se todas as figuras mostradas pertencem ao anúncio.' },
      { heading: 'Adicione chefes e criaturas grandes aos poucos', body: 'Dragões, gigantes e monstros maiores criam impacto, mas ocupam mais espaço e tendem a ser usados em momentos específicos. Escolha primeiro uma criatura relacionada ao arco atual. Uma peça grande também pode servir como elemento de exposição entre as sessões. Confira dimensões, base e escala para saber quantas casas ela deve ocupar e como será transportada sem danificar asas, chifres ou armas.' },
      { heading: 'Monte um plano de coleção por etapas', body: 'Na primeira etapa, cubra os heróis e seis a doze inimigos reutilizáveis. Na segunda, acrescente NPCs, conjuradores e criaturas relacionadas à campanha. Na terceira, invista em chefes, cenários e variações. Essa ordem melhora o aproveitamento de cada compra. Use favoritos e comparação para avaliar kits, preços e quantidades, depois confira o anúncio oficial do marketplace antes de finalizar.', items: ['Etapa 1: grupo de heróis e inimigos básicos.', 'Etapa 2: NPCs, conjuradores e criaturas do arco.', 'Etapa 3: chefes, monstros grandes e peças de exposição.', 'Registre quais tipos já existem para evitar duplicações desnecessárias.'] },
    ],
    faq: [{ question: 'Quantas miniaturas são necessárias para começar?', answer: 'Não existe número obrigatório. Um grupo de heróis e um pequeno kit de inimigos reutilizáveis já permite representar muitos encontros.' }, { question: 'Preciso ter a miniatura exata de cada monstro?', answer: 'Não. Uma peça visualmente semelhante pode representar outra criatura, desde que todos na mesa entendam a referência.' }],
    relatedGuideSlugs: ['como-jogar-dnd', 'miniaturas-rpg', 'escala-miniaturas-rpg-28mm-32mm-75mm', 'como-escolher-miniaturas-pathfinder'], categoryPath: '/miniaturas-dnd', categoryLabel: 'Ver miniaturas para D&D', productKeywords: ['d&d', 'guerreiro', 'goblin', 'esqueleto', 'mago'],
  },
  {
    slug: 'como-escolher-miniaturas-pathfinder', cluster: 'pathfinder', title: 'Como escolher miniaturas para Pathfinder', seoTitle: 'Como Escolher Miniaturas para Pathfinder', seoDescription: 'Escolha miniaturas para Pathfinder considerando personagem, criatura, escala, base e utilidade nos encontros da campanha.', updatedAt: '2026-08-09', readingMinutes: 7,
    intro: 'Pathfinder reúne personagens muito diferentes, criaturas de vários tamanhos e encontros em que posição e alcance importam. A miniatura ideal não precisa reproduzir cada detalhe da ficha, mas deve comunicar rapidamente quem está em cena. Classe, arma, postura, tamanho e base ajudam mais na mesa do que uma semelhança perfeita. Uma seleção planejada por função também pode ser aproveitada em outros sistemas de fantasia.',
    sections: [
      { heading: 'Represente a função do personagem', body: 'Observe o papel mais reconhecível do personagem: combatente, especialista, conjurador ou suporte. Um mago pode ser identificado por cajado, livro ou efeito mágico; um patrulheiro, por arco e equipamento de exploração. Ancestralidade e armadura ajudam na personalização, mas não precisam limitar a escolha. Priorize uma silhueta fácil de reconhecer entre outras peças da mesma escala.', items: ['Liste classe, arma principal e característica visual.', 'Compare a pose com a personalidade do personagem.', 'Confirme se a base funciona no mapa utilizado pelo grupo.'] },
      { heading: 'Considere tamanho e espaço ocupado', body: 'Criaturas pequenas, médias, grandes e enormes ocupam áreas diferentes. A medida em milímetros costuma indicar a referência da escultura, enquanto a base mostra melhor o espaço necessário no mapa. Uma miniatura alta e estreita pode usar uma base comum; uma criatura baixa e larga pode exigir várias casas. Confira fotografias, dimensões e ficha técnica antes de decidir.' },
      { heading: 'Crie famílias de inimigos', body: 'Em vez de comprar peças isoladas sem relação, monte grupos que funcionem juntos: goblins e líderes, esqueletos e necromantes, guerreiros e arqueiros, mortos-vivos e criaturas maiores. Essa organização facilita encontros temáticos e aumenta o reaproveitamento. Kits podem oferecer variedade de poses, mas confirme quantidade, material, pintura e conteúdo diretamente no anúncio.' },
      { heading: 'Combine utilidade e acabamento', body: 'Peças sem pintura permitem personalização para facções e personagens específicos. Peças prontas economizam tempo, quando essa condição estiver claramente informada. A resina favorece detalhes, mas exige cuidado com partes finas. Compare produtos da mesma categoria, salve os mais adequados e escolha com base na campanha atual. Preço e estoque podem mudar, portanto o anúncio sincronizado continua sendo a referência final.', items: ['Comece pelos personagens usados em todas as sessões.', 'Adicione inimigos recorrentes antes de criaturas raras.', 'Reserve peças grandes para encontros planejados.', 'Armazene cada grupo de forma que armas e detalhes não sofram pressão.'] },
    ],
    faq: [{ question: 'Miniaturas de D&D funcionam em Pathfinder?', answer: 'Em muitos casos, sim. Verifique escala, base e tamanho da criatura, pois temas e proporções podem ser compartilhados entre sistemas.' }, { question: 'Como representar criaturas grandes?', answer: 'Use uma base compatível com o espaço ocupado e confirme as dimensões finais da peça antes da compra.' }],
    relatedGuideSlugs: ['miniaturas-rpg', 'miniaturas-para-comecar-campanha-dnd', 'escala-miniaturas-rpg-28mm-32mm-75mm'], categoryPath: '/miniaturas-pathfinder', categoryLabel: 'Ver miniaturas para Pathfinder', productKeywords: ['pathfinder', 'goblin', 'esqueleto', 'necromante'],
  },
  {
    slug: 'cuidados-miniaturas-resina', cluster: 'miniaturas', title: 'Como cuidar e conservar miniaturas de resina', seoTitle: 'Cuidados com Miniaturas de Resina: Conservação', seoDescription: 'Saiba como guardar, limpar, transportar e conservar miniaturas de resina, protegendo pintura e detalhes delicados.', updatedAt: '2026-08-09', readingMinutes: 7,
    intro: 'Miniaturas de resina podem conservar detalhes por muitos anos quando são manuseadas e armazenadas com atenção. Armas, dedos, chifres, asas e cajados concentram tensão em áreas pequenas e merecem cuidado especial. O maior risco geralmente não está no uso normal, mas em quedas, calor, pressão durante o transporte e produtos de limpeza inadequados. Uma rotina simples reduz danos sem transformar a coleção em algo que não possa ser usado.',
    sections: [
      { heading: 'Manuseie pela base', body: 'Sempre que a peça possuir base, use-a como ponto principal de apoio. Evite levantar a miniatura por espada, asa, arco ou acessório. Antes de mover várias peças, prepare uma superfície livre e estável. Durante partidas, mantenha bebidas e objetos pesados afastados do tabuleiro. Se uma parte parecer flexível ou frágil, não force para corrigir a posição sem consultar a orientação do fabricante.', items: ['Mãos limpas reduzem transferência de gordura para a pintura.', 'Apoie peças grandes com as duas mãos.', 'Não empilhe miniaturas soltas.'] },
      { heading: 'Proteja contra calor, sol e umidade', body: 'Calor excessivo pode alterar materiais e colas, enquanto luz solar direta pode afetar cores ao longo do tempo. Prefira estantes afastadas de janelas muito quentes e ambientes com variação intensa. Umidade também pode prejudicar bases, cenários e embalagens. Se a miniatura estiver pintada, considere uma vitrine ou caixa que reduza poeira sem criar pressão sobre os detalhes.' },
      { heading: 'Limpeza sem perder acabamento', body: 'Para poeira leve, use pincel macio e movimentos delicados. Evite produtos químicos, solventes ou imersão sem saber como eles reagem com resina, primer, tinta, cola e verniz. Uma peça pintada pode exigir cuidados diferentes de uma peça sem pintura. Quando houver sujeira persistente, consulte as instruções do vendedor ou do material utilizado no acabamento antes de tentar uma limpeza mais agressiva.' },
      { heading: 'Transporte e pequenos acidentes', body: 'Caixas rígidas com divisórias evitam que as peças se choquem. Espuma, suportes magnéticos ou bandejas podem ajudar, desde que não pressionem partes salientes. Transporte criaturas grandes separadamente quando necessário. Se ocorrer quebra, guarde todas as partes e identifique o material antes de escolher adesivo ou técnica de reparo. Um conserto apressado pode manchar a pintura ou desalinhá-la.', items: ['Fotografe a montagem antes de desmontar peças removíveis.', 'Separe miniaturas por tamanho e fragilidade.', 'Verifique a caixa antes de fechar para não prender armas ou asas.', 'Mantenha a coleção longe de crianças pequenas e animais.'] },
    ],
    faq: [{ question: 'Posso lavar uma miniatura de resina pintada?', answer: 'Não faça isso sem conhecer a tinta, o verniz e as orientações do fabricante. Para poeira, prefira inicialmente um pincel macio.' }, { question: 'Como transportar miniaturas com segurança?', answer: 'Use uma caixa rígida com divisórias ou suporte apropriado, evitando contato e pressão sobre partes finas.' }],
    relatedGuideSlugs: ['miniaturas-rpg', 'como-pintar-miniaturas-resina', 'escala-miniaturas-rpg-28mm-32mm-75mm'], categoryPath: '/miniaturas-resina', categoryLabel: 'Explorar miniaturas em resina', productKeywords: ['resina', 'miniatura', 'figure'],
  },
]

export const guideBySlug = (slug: string) => GUIDES.find((guide) => guide.slug === slug)
export const pillarGuide = () => GUIDES.find((guide) => guide.pillar)
export const clusterById = (id: GuideClusterId) => GUIDE_CLUSTERS.find((cluster) => cluster.id === id)

/** Guias agrupados por cluster, na ordem de GUIDE_CLUSTERS, sem clusters vazios. */
export function guidesByCluster(guides: EditorialGuide[] = GUIDES) {
  return GUIDE_CLUSTERS.map((cluster) => ({ cluster, guides: guides.filter((guide) => guide.cluster === cluster.id && !guide.pillar) })).filter((group) => group.guides.length > 0)
}

export const productsForGuide = (guide: EditorialGuide, products: Product[]) => products.filter((product) => {
  if (product.status !== 'published' || product.showOnStorefront === false || !product.images.length || !product.listings.some((listing) => listing.active)) return false
  const searchable = `${product.storefrontTitle || product.title} ${product.description} ${product.category} ${Object.values(product.attributes).join(' ')}`.toLowerCase()
  return guide.productKeywords.some((keyword) => searchable.includes(keyword.toLowerCase()))
})
