import type { Product } from '../domain/product.ts'

export type EditorialGuide = {
  slug: string
  title: string
  seoTitle: string
  seoDescription: string
  updatedAt: string
  readingMinutes: number
  intro: string
  sections: Array<{ heading: string; body: string; items?: string[] }>
  faq: Array<{ question: string; answer: string }>
  relatedGuideSlugs: string[]
  categoryPath: string
  categoryLabel: string
  productKeywords: string[]
}

export const GUIDES: EditorialGuide[] = [
  {
    slug: 'escala-miniaturas-rpg-28mm-32mm-75mm', title: 'Escala de miniaturas RPG: diferenças entre 28 mm, 32 mm e 75 mm', seoTitle: 'Escala de Miniaturas RPG: 28mm, 32mm e 75mm', seoDescription: 'Entenda as diferenças entre miniaturas RPG de 28 mm, 32 mm e 75 mm e escolha a escala certa para mapas, pintura e coleção.', updatedAt: '2026-08-09', readingMinutes: 8,
    intro: 'A escala influencia como a miniatura ocupa o mapa, combina com outras peças e mostra detalhes depois da pintura. Embora os anúncios usem medidas como 28 mm, 32 mm e 75 mm, esses números nem sempre representam a altura total até a ponta de uma espada ou de um chifre. Eles funcionam como referência para comparar personagens humanos, bases e proporções. Antes de escolher, observe o uso principal: campanha, wargame, pintura ou exposição.',
    sections: [
      { heading: 'O que a medida realmente significa', body: 'Em miniaturas de personagens, a medida costuma partir dos pés até a linha dos olhos ou até o topo da cabeça. Fabricantes e escultores podem adotar referências diferentes. Uma pose curvada, um elmo alto ou uma arma levantada altera a altura final sem mudar a escala do personagem. Por isso, a ficha técnica, a fotografia ao lado de uma base e as dimensões informadas no anúncio são mais seguras do que interpretar apenas o número do título.', items: ['Compare a altura do personagem, não somente o cenário ou a arma.', 'Confira o diâmetro da base quando usar mapas quadriculados.', 'Para formar um grupo, prefira peças da mesma referência visual.'] },
      { heading: 'Quando escolher 28 mm ou 32 mm', body: 'As escalas de 28 mm e 32 mm são comuns em RPG de mesa e wargames porque equilibram leitura visual e espaço no tabuleiro. A miniatura de 32 mm normalmente apresenta presença um pouco maior e facilita a visualização de rosto, armadura e acessórios. Em muitas mesas as duas medidas convivem, mas a diferença pode aparecer quando personagens semelhantes ficam lado a lado. Monstros e criaturas naturalmente podem ser maiores sem quebrar a coerência da cena.' },
      { heading: 'Para que serve uma miniatura de 75 mm', body: 'Peças de 75 mm oferecem superfície maior para técnicas de pintura, luz, sombra e acabamento. Elas funcionam bem como projetos de exposição, chefes marcantes, criaturas grandes ou presentes para colecionadores. Em um mapa tradicional, porém, podem ocupar várias casas e exigir uma base maior. Antes de comprar, confira se a intenção é usar a peça durante encontros táticos ou mantê-la como destaque na estante e em sessões especiais.' },
      { heading: 'Checklist antes da compra', body: 'Uma escolha segura considera escala, dimensões finais, base, material e quantidade. Consulte todas as imagens do produto e leia o conteúdo da embalagem. Se o anúncio mostrar várias figuras, confirme se a venda inclui o conjunto completo. Na Distrito Geek, o preço e a disponibilidade vêm do anúncio sincronizado, mas medidas e condições finais devem ser conferidas no marketplace antes de concluir a compra.', items: ['Defina se a peça será usada no mapa, pintada ou exposta.', 'Compare com miniaturas que você já possui.', 'Verifique base, pose, altura total e quantidade.', 'Abra o anúncio oficial para confirmar a condição atual.'] },
    ],
    faq: [{ question: 'Miniaturas de 28 mm e 32 mm podem ser usadas juntas?', answer: 'Podem, principalmente quando representam criaturas e personagens de alturas diferentes. Para grupos visualmente uniformes, compare as dimensões e as bases.' }, { question: 'Uma miniatura 75 mm cabe em mapa de RPG?', answer: 'Depende da base e da função da peça. Ela pode representar uma criatura grande, mas geralmente ocupa mais espaço que um personagem comum.' }],
    relatedGuideSlugs: ['como-pintar-miniaturas-resina', 'miniaturas-para-comecar-campanha-dnd'], categoryPath: '/miniaturas-rpg-32mm', categoryLabel: 'Ver miniaturas por escala', productKeywords: ['32mm', '75mm', 'miniatura'],
  },
  {
    slug: 'como-pintar-miniaturas-resina', title: 'Como preparar e pintar miniaturas de resina', seoTitle: 'Como Pintar Miniaturas de Resina: Guia Prático', seoDescription: 'Aprenda a preparar, aplicar primer e pintar miniaturas de resina com segurança, preservando detalhes e melhorando o acabamento.', updatedAt: '2026-08-09', readingMinutes: 9,
    intro: 'Pintar uma miniatura de resina transforma uma peça sem pintura em personagem, criatura ou item de coleção. O resultado depende menos de equipamentos caros e mais de uma preparação cuidadosa, camadas finas e tempo de secagem. A resina costuma registrar detalhes muito pequenos, então excesso de tinta ou manuseio inadequado pode esconder justamente o que torna a escultura interessante. Este roteiro ajuda iniciantes a organizar o processo sem prometer um acabamento instantâneo.',
    sections: [
      { heading: 'Inspecione e prepare a peça', body: 'Comece observando a miniatura sob boa iluminação. Procure suportes remanescentes, pequenas rebarbas e pontos que precisem de limpeza. Use ferramentas adequadas, movimentos leves e proteção para evitar danificar partes finas. Não lixe resina sem os cuidados apropriados para partículas. Se o fabricante recomendar lavagem, siga a orientação do anúncio e deixe a peça secar completamente antes de aplicar qualquer produto.', items: ['Leia as orientações específicas do vendedor.', 'Trabalhe em local ventilado e bem iluminado.', 'Proteja mãos, olhos e vias respiratórias conforme a atividade.', 'Teste qualquer produto em uma área discreta.'] },
      { heading: 'Primer e aderência da tinta', body: 'O primer cria uma superfície mais uniforme para a tinta. Aplique camadas leves, mantendo distância e movimentação constantes quando usar spray. Uma camada espessa pode preencher texturas de tecido, escamas e armaduras. Escolha uma cor de primer coerente com o resultado: tons escuros ajudam sombras profundas, enquanto tons claros favorecem cores luminosas. Aguarde a cura recomendada pelo fabricante antes de começar a pintura.' },
      { heading: 'Construa a cor em camadas finas', body: 'Tintas acrílicas próprias para miniaturas oferecem controle, mas normalmente precisam de diluição compatível com a técnica. Em vez de tentar cobrir tudo em uma passada, aplique duas ou três camadas finas. Comece pelas áreas maiores, avance para detalhes e corrija bordas no final. Lavagens ajudam a marcar recessos; pincel seco pode destacar texturas, desde que usado com moderação. Fotografe etapas para perceber contrastes que passam despercebidos de perto.' },
      { heading: 'Finalização e conservação', body: 'Depois de concluir a pintura, deixe todas as camadas secarem. Um verniz compatível pode proteger a peça de manuseio, mas altera o brilho e deve ser aplicado conforme a recomendação do produto. Segure miniaturas pela base sempre que possível. Evite sol intenso, calor e quedas. Para peças usadas em campanha, uma caixa com divisórias reduz atrito entre espadas, cajados e outras partes delicadas durante o transporte.', items: ['Finalize olhos e pequenos detalhes somente com a base de cores pronta.', 'Use verniz fosco, acetinado ou brilhante conforme o efeito desejado.', 'Guarde a miniatura limpa, seca e sem pressão sobre partes finas.'] },
    ],
    faq: [{ question: 'É obrigatório usar primer em miniaturas de resina?', answer: 'É altamente recomendável porque melhora a aderência e ajuda a criar uma base uniforme, mas siga sempre as orientações do material e do fabricante.' }, { question: 'Qual tinta usar em miniaturas de resina?', answer: 'Tintas acrílicas formuladas para modelismo e miniaturas são uma escolha comum. Teste compatibilidade e trabalhe em camadas finas.' }],
    relatedGuideSlugs: ['escala-miniaturas-rpg-28mm-32mm-75mm', 'cuidados-miniaturas-resina'], categoryPath: '/miniaturas-resina', categoryLabel: 'Explorar miniaturas em resina', productKeywords: ['resina', 'sem pintura', 'miniatura'],
  },
  {
    slug: 'miniaturas-para-comecar-campanha-dnd', title: 'Quais miniaturas comprar para começar uma campanha de D&D', seoTitle: 'Miniaturas para Começar uma Campanha de D&D', seoDescription: 'Veja quais heróis, criaturas e kits priorizar ao montar a primeira seleção de miniaturas para uma campanha de D&D.', updatedAt: '2026-08-09', readingMinutes: 8,
    intro: 'Uma primeira coleção de miniaturas para D&D não precisa representar todos os monstros do livro. O conjunto mais útil é aquele que aparece repetidamente: personagens dos jogadores, inimigos versáteis e algumas criaturas que marcam encontros importantes. Planejar por função evita comprar peças bonitas que raramente chegam à mesa. Comece pelo próximo arco da campanha e amplie a coleção conforme os desafios realmente aparecem.',
    sections: [
      { heading: 'Priorize o grupo de aventureiros', body: 'Os personagens dos jogadores são as peças mais utilizadas. Procure representar classe, equipamento e personalidade sem exigir uma correspondência perfeita. Guerreiro, ladino, clérigo, patrulheiro, bárbaro e mago formam uma base versátil para diferentes grupos. Se os personagens mudarem de equipamento durante a campanha, a miniatura ainda pode funcionar como referência visual. O objetivo é facilitar posições, alcance e identificação durante o encontro.', items: ['Escolha silhuetas diferentes para reconhecer cada personagem.', 'Considere a escala e o tamanho das bases.', 'Converse com os jogadores antes de definir a aparência.'] },
      { heading: 'Escolha inimigos que possam ser reutilizados', body: 'Goblins, esqueletos, mortos-vivos e guerreiros genéricos aparecem em muitos cenários e podem representar criaturas semelhantes quando necessário. Kits com poses variadas dão movimento ao encontro e costumam ser mais úteis do que várias cópias idênticas. Antes de comprar um conjunto, confira a quantidade exata, as peças incluídas e se todas as figuras mostradas pertencem ao anúncio.' },
      { heading: 'Adicione chefes e criaturas grandes aos poucos', body: 'Dragões, gigantes e monstros maiores criam impacto, mas ocupam mais espaço e tendem a ser usados em momentos específicos. Escolha primeiro uma criatura relacionada ao arco atual. Uma peça grande também pode servir como elemento de exposição entre as sessões. Confira dimensões, base e escala para saber quantas casas ela deve ocupar e como será transportada sem danificar asas, chifres ou armas.' },
      { heading: 'Monte um plano de coleção por etapas', body: 'Na primeira etapa, cubra os heróis e seis a doze inimigos reutilizáveis. Na segunda, acrescente NPCs, conjuradores e criaturas relacionadas à campanha. Na terceira, invista em chefes, cenários e variações. Essa ordem melhora o aproveitamento de cada compra. Use favoritos e comparação para avaliar kits, preços e quantidades, depois confira o anúncio oficial do marketplace antes de finalizar.', items: ['Etapa 1: grupo de heróis e inimigos básicos.', 'Etapa 2: NPCs, conjuradores e criaturas do arco.', 'Etapa 3: chefes, monstros grandes e peças de exposição.', 'Registre quais tipos já existem para evitar duplicações desnecessárias.'] },
    ],
    faq: [{ question: 'Quantas miniaturas são necessárias para começar?', answer: 'Não existe número obrigatório. Um grupo de heróis e um pequeno kit de inimigos reutilizáveis já permite representar muitos encontros.' }, { question: 'Preciso ter a miniatura exata de cada monstro?', answer: 'Não. Uma peça visualmente semelhante pode representar outra criatura, desde que todos na mesa entendam a referência.' }],
    relatedGuideSlugs: ['escala-miniaturas-rpg-28mm-32mm-75mm', 'como-escolher-miniaturas-pathfinder'], categoryPath: '/miniaturas-dnd', categoryLabel: 'Ver miniaturas para D&D', productKeywords: ['d&d', 'guerreiro', 'goblin', 'esqueleto', 'mago'],
  },
  {
    slug: 'como-escolher-miniaturas-pathfinder', title: 'Como escolher miniaturas para Pathfinder', seoTitle: 'Como Escolher Miniaturas para Pathfinder', seoDescription: 'Escolha miniaturas para Pathfinder considerando personagem, criatura, escala, base e utilidade nos encontros da campanha.', updatedAt: '2026-08-09', readingMinutes: 7,
    intro: 'Pathfinder reúne personagens muito diferentes, criaturas de vários tamanhos e encontros em que posição e alcance importam. A miniatura ideal não precisa reproduzir cada detalhe da ficha, mas deve comunicar rapidamente quem está em cena. Classe, arma, postura, tamanho e base ajudam mais na mesa do que uma semelhança perfeita. Uma seleção planejada por função também pode ser aproveitada em outros sistemas de fantasia.',
    sections: [
      { heading: 'Represente a função do personagem', body: 'Observe o papel mais reconhecível do personagem: combatente, especialista, conjurador ou suporte. Um mago pode ser identificado por cajado, livro ou efeito mágico; um patrulheiro, por arco e equipamento de exploração. Ancestralidade e armadura ajudam na personalização, mas não precisam limitar a escolha. Priorize uma silhueta fácil de reconhecer entre outras peças da mesma escala.', items: ['Liste classe, arma principal e característica visual.', 'Compare a pose com a personalidade do personagem.', 'Confirme se a base funciona no mapa utilizado pelo grupo.'] },
      { heading: 'Considere tamanho e espaço ocupado', body: 'Criaturas pequenas, médias, grandes e enormes ocupam áreas diferentes. A medida em milímetros costuma indicar a referência da escultura, enquanto a base mostra melhor o espaço necessário no mapa. Uma miniatura alta e estreita pode usar uma base comum; uma criatura baixa e larga pode exigir várias casas. Confira fotografias, dimensões e ficha técnica antes de decidir.' },
      { heading: 'Crie famílias de inimigos', body: 'Em vez de comprar peças isoladas sem relação, monte grupos que funcionem juntos: goblins e líderes, esqueletos e necromantes, guerreiros e arqueiros, mortos-vivos e criaturas maiores. Essa organização facilita encontros temáticos e aumenta o reaproveitamento. Kits podem oferecer variedade de poses, mas confirme quantidade, material, pintura e conteúdo diretamente no anúncio.' },
      { heading: 'Combine utilidade e acabamento', body: 'Peças sem pintura permitem personalização para facções e personagens específicos. Peças prontas economizam tempo, quando essa condição estiver claramente informada. A resina favorece detalhes, mas exige cuidado com partes finas. Compare produtos da mesma categoria, salve os mais adequados e escolha com base na campanha atual. Preço e estoque podem mudar, portanto o anúncio sincronizado continua sendo a referência final.', items: ['Comece pelos personagens usados em todas as sessões.', 'Adicione inimigos recorrentes antes de criaturas raras.', 'Reserve peças grandes para encontros planejados.', 'Armazene cada grupo de forma que armas e detalhes não sofram pressão.'] },
    ],
    faq: [{ question: 'Miniaturas de D&D funcionam em Pathfinder?', answer: 'Em muitos casos, sim. Verifique escala, base e tamanho da criatura, pois temas e proporções podem ser compartilhados entre sistemas.' }, { question: 'Como representar criaturas grandes?', answer: 'Use uma base compatível com o espaço ocupado e confirme as dimensões finais da peça antes da compra.' }],
    relatedGuideSlugs: ['miniaturas-para-comecar-campanha-dnd', 'escala-miniaturas-rpg-28mm-32mm-75mm'], categoryPath: '/miniaturas-pathfinder', categoryLabel: 'Ver miniaturas para Pathfinder', productKeywords: ['pathfinder', 'goblin', 'esqueleto', 'necromante'],
  },
  {
    slug: 'cuidados-miniaturas-resina', title: 'Como cuidar e conservar miniaturas de resina', seoTitle: 'Cuidados com Miniaturas de Resina: Conservação', seoDescription: 'Saiba como guardar, limpar, transportar e conservar miniaturas de resina, protegendo pintura e detalhes delicados.', updatedAt: '2026-08-09', readingMinutes: 7,
    intro: 'Miniaturas de resina podem conservar detalhes por muitos anos quando são manuseadas e armazenadas com atenção. Armas, dedos, chifres, asas e cajados concentram tensão em áreas pequenas e merecem cuidado especial. O maior risco geralmente não está no uso normal, mas em quedas, calor, pressão durante o transporte e produtos de limpeza inadequados. Uma rotina simples reduz danos sem transformar a coleção em algo que não possa ser usado.',
    sections: [
      { heading: 'Manuseie pela base', body: 'Sempre que a peça possuir base, use-a como ponto principal de apoio. Evite levantar a miniatura por espada, asa, arco ou acessório. Antes de mover várias peças, prepare uma superfície livre e estável. Durante partidas, mantenha bebidas e objetos pesados afastados do tabuleiro. Se uma parte parecer flexível ou frágil, não force para corrigir a posição sem consultar a orientação do fabricante.', items: ['Mãos limpas reduzem transferência de gordura para a pintura.', 'Apoie peças grandes com as duas mãos.', 'Não empilhe miniaturas soltas.'] },
      { heading: 'Proteja contra calor, sol e umidade', body: 'Calor excessivo pode alterar materiais e colas, enquanto luz solar direta pode afetar cores ao longo do tempo. Prefira estantes afastadas de janelas muito quentes e ambientes com variação intensa. Umidade também pode prejudicar bases, cenários e embalagens. Se a miniatura estiver pintada, considere uma vitrine ou caixa que reduza poeira sem criar pressão sobre os detalhes.' },
      { heading: 'Limpeza sem perder acabamento', body: 'Para poeira leve, use pincel macio e movimentos delicados. Evite produtos químicos, solventes ou imersão sem saber como eles reagem com resina, primer, tinta, cola e verniz. Uma peça pintada pode exigir cuidados diferentes de uma peça sem pintura. Quando houver sujeira persistente, consulte as instruções do vendedor ou do material utilizado no acabamento antes de tentar uma limpeza mais agressiva.' },
      { heading: 'Transporte e pequenos acidentes', body: 'Caixas rígidas com divisórias evitam que as peças se choquem. Espuma, suportes magnéticos ou bandejas podem ajudar, desde que não pressionem partes salientes. Transporte criaturas grandes separadamente quando necessário. Se ocorrer quebra, guarde todas as partes e identifique o material antes de escolher adesivo ou técnica de reparo. Um conserto apressado pode manchar a pintura ou desalinhá-la.', items: ['Fotografe a montagem antes de desmontar peças removíveis.', 'Separe miniaturas por tamanho e fragilidade.', 'Verifique a caixa antes de fechar para não prender armas ou asas.', 'Mantenha a coleção longe de crianças pequenas e animais.'] },
    ],
    faq: [{ question: 'Posso lavar uma miniatura de resina pintada?', answer: 'Não faça isso sem conhecer a tinta, o verniz e as orientações do fabricante. Para poeira, prefira inicialmente um pincel macio.' }, { question: 'Como transportar miniaturas com segurança?', answer: 'Use uma caixa rígida com divisórias ou suporte apropriado, evitando contato e pressão sobre partes finas.' }],
    relatedGuideSlugs: ['como-pintar-miniaturas-resina', 'escala-miniaturas-rpg-28mm-32mm-75mm'], categoryPath: '/miniaturas-resina', categoryLabel: 'Explorar miniaturas em resina', productKeywords: ['resina', 'miniatura', 'figure'],
  },
]

export const guideBySlug = (slug: string) => GUIDES.find((guide) => guide.slug === slug)
export const productsForGuide = (guide: EditorialGuide, products: Product[]) => products.filter((product) => {
  if (product.status !== 'published' || product.showOnStorefront === false || !product.images.length || !product.listings.some((listing) => listing.active)) return false
  const searchable = `${product.storefrontTitle || product.title} ${product.description} ${product.category} ${Object.values(product.attributes).join(' ')}`.toLowerCase()
  return guide.productKeywords.some((keyword) => searchable.includes(keyword.toLowerCase()))
})
