import type { Product } from '../domain/product'
import { isPublicProduct } from '../domain/storefront-presentation'

/**
 * `guideSlugs` é curadoria manual, não casamento automático: a landing é a porta de
 * entrada orgânica da categoria, e mandar o visitante para um guia fora do tema custa
 * mais do que não mostrar bloco nenhum. Os slugs são validados contra GUIDE_INDEX em teste.
 */
export type SeoLandingDefinition = { path: string; title: string; description: string; h1: string; intro: string; sections: Array<{ heading: string; body: string }>; faq: Array<{ question: string; answer: string }>; relatedPaths: string[]; guideSlugs: string[]; guidesHeading?: string; matches: (product: Product) => boolean }
const searchable = (product: Product) => `${product.category} ${product.marketplaceTitle || product.title} ${product.description} ${Object.values(product.attributes).join(' ')}`.toLowerCase()
const contains = (pattern: RegExp) => (product: Product) => pattern.test(searchable(product))

export const SEO_LANDINGS: SeoLandingDefinition[] = [
  { path: '/miniaturas-rpg', title: 'Miniaturas RPG em Resina para D&D e Pathfinder', description: 'Explore miniaturas RPG em resina para D&D, Pathfinder e wargames, com detalhes e compra nos anúncios oficiais.', h1: 'Miniaturas RPG em Resina', intro: 'Encontre personagens, criaturas e exércitos para campanhas, coleções e mesas de RPG. Compare os detalhes e escolha o anúncio oficial do marketplace.', sections: [{ heading: 'Como escolher miniaturas para RPG', body: 'Considere a escala, o material, o tamanho da base e o estilo da campanha. A resina favorece detalhes de armaduras, criaturas e cenários.' }, { heading: 'Peças para campanha e coleção', body: 'Além do uso em mesa, as peças podem compor dioramas e coleções. Consulte sempre as medidas no anúncio oficial.' }], faq: [{ question: 'As miniaturas são pintadas?', answer: 'A condição varia por produto. Confira a descrição e as imagens do anúncio oficial.' }], guideSlugs: ['miniaturas-rpg', 'escala-miniaturas-rpg-28mm-32mm-75mm', 'como-pintar-miniaturas-resina', 'cuidados-miniaturas-resina', 'miniaturas-essenciais-mestre-rpg'], relatedPaths: ['/miniaturas-dnd', '/miniaturas-pathfinder', '/miniaturas-rpg-32mm', '/miniaturas-resina'], matches: contains(/miniatura|rpg|wargame|goblin|esqueleto|ghoul/) },
  { path: '/miniaturas-dnd', title: 'Miniaturas para D&D em Resina', description: 'Miniaturas para aventuras de D&D, personagens e criaturas em resina com links para anúncios oficiais.', h1: 'Miniaturas para D&D', intro: 'Selecione heróis, inimigos e criaturas para representar encontros e personagens em campanhas de fantasia.', sections: [{ heading: 'Representando encontros de D&D', body: 'Uma seleção coerente ajuda jogadores e mestres a visualizar posições, criaturas e momentos importantes.' }], faq: [{ question: 'Posso usar as peças em outros sistemas?', answer: 'Sim. Verifique escala e dimensões; muitas miniaturas funcionam em diferentes sistemas.' }], guideSlugs: ['miniaturas-para-comecar-campanha-dnd', 'como-jogar-dnd', 'escala-miniaturas-rpg-28mm-32mm-75mm', 'miniaturas-rpg'], relatedPaths: ['/miniaturas-rpg', '/miniaturas-rpg-32mm'], matches: contains(/d\s*&\s*d|dungeons|dragons/) },
  { path: '/miniaturas-pathfinder', title: 'Miniaturas Pathfinder para RPG', description: 'Conheça miniaturas compatíveis com campanhas de Pathfinder e outros sistemas de fantasia.', h1: 'Miniaturas para Pathfinder', intro: 'Explore personagens e criaturas para encontros táticos e coleções inspiradas em fantasia.', sections: [{ heading: 'Escolhas para sua campanha', body: 'Observe a função do personagem, o tipo de criatura e a escala indicada para manter o conjunto consistente.' }], faq: [{ question: 'As miniaturas servem em mapas quadriculados?', answer: 'Consulte a escala e o tamanho da base no anúncio para confirmar.' }], guideSlugs: ['como-escolher-miniaturas-pathfinder', 'dnd-vs-pathfinder', 'miniaturas-rpg'], relatedPaths: ['/miniaturas-rpg', '/miniaturas-dnd'], matches: contains(/pathfinder/) },
  { path: '/miniaturas-rpg-32mm', title: 'Miniaturas RPG 32mm em Resina', description: 'Miniaturas RPG em escala aproximada de 32mm para personagens, monstros e exércitos.', h1: 'Miniaturas RPG 32mm', intro: 'A escala 32mm é comum em mesas e wargames por equilibrar presença visual e espaço de jogo.', sections: [{ heading: 'Entenda a escala 32mm', body: 'A medida normalmente descreve uma altura de referência. Bases, poses e criaturas podem alterar as dimensões finais.' }], faq: [{ question: 'Todas as figuras têm exatamente 32mm?', answer: 'Não necessariamente. Confirme as medidas específicas no anúncio.' }], guideSlugs: ['escala-miniaturas-rpg-28mm-32mm-75mm', 'miniaturas-rpg', 'miniaturas-para-comecar-campanha-dnd'], relatedPaths: ['/miniaturas-rpg', '/miniaturas-resina'], matches: contains(/32\s*mm/) },
  { path: '/miniaturas-resina', title: 'Miniaturas em Resina com Alto Nível de Detalhe', description: 'Veja miniaturas em resina para RPG, decoração e coleção, com imagens e condições dos anúncios oficiais.', h1: 'Miniaturas em Resina', intro: 'A resina favorece detalhes finos em personagens, armaduras e criaturas. Compare acabamento e medidas.', sections: [{ heading: 'Cuidados com peças em resina', body: 'Evite quedas, calor excessivo e esforço em partes finas. Para pintura, siga a preparação indicada ao material.' }], faq: [{ question: 'Resina é resistente?', answer: 'É detalhada, mas pode exigir mais cuidado que plásticos flexíveis.' }], guideSlugs: ['como-pintar-miniaturas-resina', 'cuidados-miniaturas-resina', 'miniaturas-rpg'], relatedPaths: ['/miniaturas-rpg', '/miniaturas-rpg-32mm'], matches: contains(/resina/) },
  { path: '/kits-rpg', title: 'Kits de Miniaturas RPG e Exércitos', description: 'Kits de miniaturas e exércitos para ampliar campanhas, encontros e coleções de RPG.', h1: 'Kits de Miniaturas RPG', intro: 'Conjuntos são úteis para montar grupos de inimigos, tropas e encontros completos.', sections: [{ heading: 'Como escolher um kit', body: 'Compare quantidade de peças, variedade de poses, escala e tema. Confirme o conteúdo no anúncio oficial.' }], faq: [{ question: 'O kit inclui todas as peças das imagens?', answer: 'Confira a lista de conteúdo no anúncio, que é a referência final.' }], guideSlugs: ['miniaturas-essenciais-mestre-rpg', 'criar-encontros-rpg', 'goblins-rpg', 'mortos-vivos-rpg'], relatedPaths: ['/miniaturas-rpg', '/miniaturas-rpg-32mm'], matches: contains(/\bkit\b|ex[eé]rcito|conjunto|lote/) },
  { path: '/action-figures', title: 'Action Figures e Colecionáveis Geek', description: 'Action figures, personagens e colecionáveis para decorar sua estante e ampliar sua coleção.', h1: 'Action Figures e Colecionáveis', intro: 'Descubra personagens e peças decorativas com imagens reais e direcionamento para anúncios oficiais.', sections: [{ heading: 'Como escolher uma peça para coleção', body: 'Observe dimensões, material, acabamento e espaço disponível. Compare as imagens antes de decidir.' }], faq: [{ question: 'A compra é feita na Distrito Geek?', answer: 'A Distrito Geek funciona como vitrine. A compra é concluída no marketplace indicado.' }], guideSlugs: ['cuidados-miniaturas-resina', 'como-pintar-miniaturas-resina'], guidesHeading: 'Aprenda mais sobre peças em resina', relatedPaths: ['/miniaturas-resina'], matches: contains(/action.?figure|figure|anime|pokemon|colecion|decorativ/) },
]

export const landingByPath = (path: string) => SEO_LANDINGS.find((landing) => landing.path === path)
export const productsForLanding = (landing: SeoLandingDefinition, products: Product[]) => products.filter((product) => isPublicProduct(product) && landing.matches(product))
export const landingForProduct = (product: Product) => SEO_LANDINGS.find((landing) => landing.matches(product)) || SEO_LANDINGS[0]
