import { ChartBar, SignOut, UploadSimple } from '@phosphor-icons/react'
import { FormEvent, useEffect, useState } from 'react'
import * as XLSX from 'xlsx'
import type { Marketplace, Product } from '../domain/product'
import { normalizeMarketplaceRow } from '../import/normalize-row'

const messageOf = (value: unknown) => typeof value === 'string' ? value : value && typeof value === 'object' && 'message' in value && typeof value.message === 'string' ? value.message : 'Não foi possível concluir. Tente novamente.'
const slugify = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

export function AdminPage() {
  const [auth, setAuth] = useState<'loading' | 'yes' | 'no'>('loading'), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [preview, setPreview] = useState<Record<string, unknown>[]>([]), [products, setProducts] = useState<Product[]>([])
  const loadProducts = async () => { const response = await fetch('/api/admin-products'); if (response.ok) setProducts((await response.json()).products || []) }
  useEffect(() => { fetch('/api/admin-session').then((response) => { setAuth(response.ok ? 'yes' : 'no'); if (response.ok) void loadProducts() }).catch(() => setAuth('no')) }, [])

  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); try { const response = await fetch('/api/admin-login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); const data = await response.json(); if (!response.ok) throw data; setAuth('yes'); await loadProducts() } catch (err) { setError(messageOf(err)) } }
  async function logout() { await fetch('/api/admin-session', { method: 'DELETE' }); setAuth('no') }
  async function readFile(file: File) { const book = XLSX.read(await file.arrayBuffer()); setPreview(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]], { defval: '' })) }
  async function confirmImport() { setError(''); const imported = preview.map((row, index) => normalizeMarketplaceRow(row, index + 2)).filter((result) => !result.ignored && result.product && !result.errors.length).map((result) => result.product!); try { const response = await fetch('/api/admin-import', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ products: imported }) }); const data = await response.json(); if (!response.ok) throw data; setNotice(`${data.accepted} anúncios importados como rascunho.`); setPreview([]); await loadProducts() } catch (err) { setError(messageOf(err)) } }
  async function createProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget), title = String(form.get('title')), marketplace = String(form.get('marketplace')) as Marketplace, url = String(form.get('url')), image = String(form.get('image')), now = new Date().toISOString(); const product: Product = { id: `manual-${crypto.randomUUID()}`, slug: `${slugify(title)}-${Date.now()}`, title, description: String(form.get('description')), price: Number(form.get('price')), currency: 'BRL', stock: Number(form.get('stock') || 0), status: 'draft', category: 'colecionaveis', images: image ? [image] : [], attributes: {}, featured: false, showOnStorefront: true, listings: [{ marketplace, externalId: `manual-${Date.now()}`, url, active: true }], version: 1, createdAt: now, updatedAt: now }; try { const response = await fetch('/api/admin-products', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(product) }); const data = await response.json(); if (!response.ok) throw data; setNotice('Anúncio salvo como rascunho.'); event.currentTarget.reset(); await loadProducts() } catch (err) { setError(messageOf(err)) } }

  if (auth === 'loading') return <main className="admin-login"><p>Validando acesso…</p></main>
  if (auth === 'no') return <main className="admin-login"><form onSubmit={login}><div className="brand"><span>DISTRITO</span><strong>GEEK</strong></div><p className="eyebrow">Painel exclusivo</p><h1>Administrar catálogo</h1><label>E-mail<input type="email" name="email" required autoComplete="username" /></label><label>Senha<input type="password" name="password" required autoComplete="current-password" /></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="button primary">Entrar</button><a href="/">Voltar ao site</a></form></main>
  return <main className="admin-shell"><aside><div className="brand small"><span>DISTRITO</span><strong>GEEK</strong></div><b>Catálogo</b><button><ChartBar /> Visão geral</button><button><UploadSimple /> Importar anúncios</button><button onClick={logout}><SignOut /> Sair</button></aside><section><header><div><p className="eyebrow">Administração</p><h1>Visão geral</h1></div><a className="button ghost" href="/">Abrir site</a></header>{notice && <div className="form-success" role="status">{notice}</div>}{error && <div className="form-error" role="alert">{error}</div>}<div className="stats"><div><span>Publicados</span><b>{products.filter((p) => p.status === 'published').length}</b></div><div><span>Pausados</span><b>{products.filter((p) => p.status === 'paused').length}</b></div><div><span>Rascunhos</span><b>{products.filter((p) => p.status === 'draft').length}</b></div></div><div className="admin-grid"><div className="admin-card"><h2>Importar anúncios em lote</h2><p>Envie CSV ou XLS exportado do Mercado Livre, Shopee ou outro marketplace. Revise antes de confirmar.</p><label className="upload"><UploadSimple /> Selecionar planilha<input hidden type="file" accept=".csv,.xls,.xlsx" onChange={(e) => e.target.files?.[0] && readFile(e.target.files[0])} /></label>{preview.length > 0 && <><p><b>{preview.length} linhas prontas para revisão</b></p><div className="table-wrap"><table><thead><tr>{Object.keys(preview[0]).slice(0, 5).map((key) => <th key={key}>{key}</th>)}</tr></thead><tbody>{preview.slice(0, 8).map((row, index) => <tr key={index}>{Object.values(row).slice(0, 5).map((value, cell) => <td key={cell}>{String(value)}</td>)}</tr>)}</tbody></table></div><button className="button primary" onClick={confirmImport}>Confirmar importação</button></>}</div><form className="admin-card manual-form" onSubmit={createProduct}><h2>Cadastrar anúncio manualmente</h2><label>Título<input name="title" required minLength={8} /></label><label>Descrição<textarea name="description" required minLength={20} /></label><div><label>Preço<input name="price" type="number" min="0.01" step="0.01" required /></label><label>Estoque<input name="stock" type="number" min="0" defaultValue="0" required /></label></div><label>Marketplace<select name="marketplace"><option value="mercado-livre">Mercado Livre</option><option value="shopee">Shopee</option></select></label><label>Link do anúncio<input name="url" type="url" required placeholder="https://..." /></label><label>URL da imagem<input name="image" type="url" placeholder="https://..." /></label><button className="button primary">Salvar rascunho</button></form></div></section></main>
}
